### ISSUE TITLE
how to use vips handler ?

### ISSUE THREAD

**Issue by ghost** [qor/media#17]
Hi guys,

Hope you are all well !

As anybody tried to use the vips handler ? Is there any code snippets/gist showing how to register the handler ?

Cheers,
X

**Comment by x0rzkov** [comment]
@azumads , thanks for the README info at https://github.com/qor/media/tree/master/handlers/vips

Bu how do you hook it to qor ? Do you have a code snippet/gist ?

**Comment by azumads** [comment]
As I wrote in readme ,

Usage
Setup media library and add below code, then it will compress jpg/png and generate webp for you.

```
import "github.com/qor/media/handlers/vips"

vips.UseVips(vips.Config{EnableGenerateWebp: true})
```

It  will replace the image crop handler in https://github.com/qor/media/blob/master/handlers.go

**Comment by x0rzkov** [comment]
Thanks for the reply !

I'll have a try because imaging is slow for my batch scripts.

Btw, I made https://paper2code.com/ with qor framework. 
So I used extensively your work guys, good job ! 👍 

Now, I just need to figure out the answer for the issue https://github.com/qor/admin/issues/223 and we are good. Can you help me on this one ?

**Comment by azumads** [comment]
sorry, don't have idea about it.

x0rzkov <notifications@github.com> 于2020年7月14日周二 下午4:14写道：

**Comment by x0rzkov** [comment]
Thanks for your reply !

**Comment by x0rzkov** [comment]
Can you ping anybody from your team who can give me a hand on that ?
